
# Note: stack tracing setup:
#   1. disable strict impl params plugin in package.yaml
#   2. enable profiling here
#   3. stack clean, stack build
#   4. customize-group > haskell > haskell-interactive > stack ghci args
#      add the following args
#      --ghci-options="-fexternal-interpreter"
#      --ghci-options="-prof"
#      --ghci-options="-fprof-auto-calls"
#   5. reload ghci

resolver: nightly-2025-09-06

packages:
- .

ghc-options:
    "$everything": -split-sections

# build:
#   library-profiling: true
#   executable-profiling: true

extra-deps:
- primdata-0.1.2.3
- dynamic-array-0.1.3
- strict-impl-params-1.1.0
